### ISSUE TITLE
Svelte Society Assets

### ISSUE THREAD

**Issue by swyxio** [sveltejs/community-legacy#108]
![Downtomeet header](https://user-images.githubusercontent.com/6764957/75638786-a87e7480-5bfb-11ea-90ef-8ea507bc0457.jpg)
![Downtoomeetlogo](https://user-images.githubusercontent.com/6764957/75638787-a87e7480-5bfb-11ea-878a-25bec4044e0b.jpg)
![Twitter Header](https://user-images.githubusercontent.com/6764957/75638788-a87e7480-5bfb-11ea-9270-7c7552a40042.jpg)
![Twitter Profile Photo](https://user-images.githubusercontent.com/6764957/75638789-a9170b00-5bfb-11ea-9d55-6a814e3a1996.jpg)

**Comment by jerriclynsjohn** [comment]
We need Vectors/Editable to customize for the rest of the chapters

**Comment by Wolfr** [comment]
See this link for the vectors: https://www.figma.com/file/RQGRxvvzEAwkANdiRtXEmv/Svelte-materials?node-id=0%3A1

**Comment by swyxio** [comment]
think we're good here, gonna close
