### ISSUE TITLE
todo: grab meetup feed from meetup dot com

### ISSUE THREAD

**Issue by swyxio** [sveltejs/community-legacy#112]
code from typescript

https://github.com/microsoft/TypeScript-website/blob/6ac6bd65097dc5bba29da868703975de9dce51db/packages/community-meta/scripts/generateRichMeetupData.js#L1

http://www.typescriptlang.org/v2/community/

**Comment by dreitzner** [comment]
Link should now be https://www.typescriptlang.org/community

**Comment by dreitzner** [comment]
closed in favor of redirect to https://sveltesociety.dev/events
