### ISSUE TITLE
Company logo policy

### ISSUE THREAD

**Issue by ryanatkn** [sveltejs/community-legacy#135]
What's a reasonable and scalable policy for including company logos on [svelte.dev](https://svelte.dev)? I'm not sure what policies are like in comparable projects. The current set of logos now overflow the vertical space on a 1080p layout and there's ~70 requests with ~400k data. When does this become a problem and what are the possible solutions? Continue taking all submissions? Maybe limit the number that are eagerly loaded and put the rest behind a click? (randomly sorted?)

**Comment by kevmodrome** [comment]
I think maybe @Conduitry @pngwn @antony can help figure this out since this concerns the Svelte website.

**Comment by Conduitry** [comment]
This is a can that's been getting kicked for a little while. We're probably just about at the point where (not to put too fine a point on it) we should only be initially listing companies that people give a shit about, with the rest hidden on their own page. Who makes this distinction and what criteria they use is, uh, an open question.

**Comment by pngwn** [comment]
Fancy tech companies or very large orgs is probably what people care about the most.

**Comment by antony** [comment]
I know I bang on about Hapi a lot, but that's because I think they execute well.

What they used to have is a limit of 40 or so, randomly ordered and cycled logos, each time you hit the page.

Even with the chance of being shown at about 20%, this drove a huge amount of traffic to my (tiny, inconsequential) startup.

I'm also not averse to having a set of ~5 hardcoded, trophy cabinet logos atop this collection.

Thoughts?

**Comment by swyxio** [comment]
@antony i like that. marquee users, and then randomized.

**Comment by Wolfr** [comment]
I would Just bring down the list to the most known/important ones. A suggestion.

* Datawrapper
* 1password
* GoDaddy
* Rakuten
* New York Times
* Mail.ru

**Comment by stephane-vanraes** [comment]
"Most known" is a very relative term, personally I have never heard of _Rakuten_ before today.  The idea of just having a limited set, randomized, sounds good to me.

Maybe with an exception for the New York Times since that is where Svelte originated ?

**Comment by Wolfr** [comment]
I mean, yeah, it is relative, but Rakuten is definitely a big company in Asia. Whereas some of the companies on the list are quite small.

If we put every companie out there the list becomes a huge block on the homepage. This leads to perf problems but also to a lack of focus. Not to mention the maintenance cost of long lists.

The goal of this homepage is to show that we have the trust of organizations with Svelte. Randomizing could be an option, but then there is a big chance that it shows 6 random companies no one has heard of. 

Another two for the list could be Microsoft and Apple. Both companies seem to be working with Svelte as well. 

What we could do is categorize the companies as primary and secondary, and then list 6-8 random primary companies on the homepage. And link to a full list of companies using Svelte on another route: `/companies-using-svelte`.

**Comment by swyxio** [comment]
as someone who lives in Asia and the US (knowing about Kobo books, ebates, and overdrive), i can vouch for Rakuten :)

**Comment by dreitzner** [comment]
with #377 all these would be easy to do.

I propose:

1. a list of a few important ones that will be always shown (at the top)
2. a randomized list that cuts of at 35 companies 
3. add a show more button that expands to all companies

With that change there would be no need to move it to it's own route (which can be easily done later on, if needed)

If @Conduitry , @pngwn  and @antony  can agree upon a list, I can start the implementation.

**Comment by antony** [comment]
I agree to the three points above, I think that's absolutely ideal.

As for who is at the top - I'd love to see household names there, Ikea (are they on there?) Decathlon (we can ping them about it), Spotify, 1Password, Chess.com, Philips, The New York Times.

If the whole thing is expressed as JSON it doesn't really matter what we put where initially, we can just rejig it as required before or after merge.

**Comment by benmccann** [comment]
In addition to the ones Antony mentioned, here are some others currently on the list that look to be fairly large: Alaska Airlines, Avast, FusionCharts, GoDaddy, Les Echos, Philips, Rakuten, RazorPay, Schneider Electric

**Comment by dreitzner** [comment]
@antony the following companies are not yet included:

- ikea
- decathlon
- spotify

Can you confirm, that I can add them with this ticket.

**Comment by antony** [comment]
It's not up to me so I would hold off for now. It would be good to contact them to ask.

**Comment by swyxio** [comment]
we should try to get Apple too but no idea who to ask 😹

**Comment by dreitzner** [comment]
with #408 companies will no longer be loaded all at once after clicking load more, but will increase by base amount with each click until the full list is loaded.

**Comment by peopledrivemecrazy** [comment]
This is something that came to my mind just now, how about links that are only `https`?

**Comment by benmccann** [comment]
We've decided to only feature the most prominent companies and no longer include community submitted sites. Thanks all

https://github.com/sveltejs/svelte/pull/6409
