### ISSUE TITLE
"Svelte Status" seems to be broken

### ISSUE THREAD

**Issue by kontrafiktion** [sveltejs/community-legacy#138]
There is a problem with the https certificate at

     http://www.sveltestatus.com/

**Comment by kontrafiktion** [comment]
contacted the owner @marlosin 

> Hi Marlos,
> 
> it looks like the web site 
> 
>   http://www.sveltestatus.com/ 
> 
> has a certificate problem (Firefox, Safari at least. 
> 
> Firefox says: 
> 
>   "sveltestatus.dev has a security policy called HTTP Strict Transport Security (HSTS)"
> 
> so it tries to redirect to "https", but the certificate given is not for sveltestatus.com but postach.io 
> 
> Do you still want to maintain this domain and even more important: Do you still publish the Svelte Newsletter?
> 
> If not I would want to remove http://www.sveltestatus.com/ from 
> 
>   https://svelte-community.netlify.com/
> 
> 
> Kind Regards
> Victor

**Comment by kontrafiktion** [comment]
Response from Marlos:

> Hi Victor!
> 
> Thanks for reaching out, please remove it from the community for now. This newsletter was being done together with a colleague, who is not available at the moment, so I don't know when we'll be able to fix it.
> 
> Kind regards,

**Comment by ryanatkn** [comment]
Thank you for looking into this!
