### ISSUE TITLE
Filter functionality broken

### ISSUE THREAD

**Issue by kevmodrome** [sveltejs/community-legacy#147]
Seems the filter functionality has gone haywire the last few days, not sure when or what happened. Couln't spot anything obvious in the few minutes I looked at it.

`ReferenceError: options is not defined`

**Comment by swyxio** [comment]
i ran into this too. need to replace `var` with `const`. not sure what happened there. i will fix in https://github.com/sveltejs/community/commit/d8a7db8ee98e45229f566c9ca0daa83705e3ef35
