### ISSUE TITLE
Support GitLab for repo stats

### ISSUE THREAD

**Issue by ryanatkn** [sveltejs/community-legacy#151]
Currently we pull stats from GitHub including `stars` and `last_updated` - https://github.com/sveltejs/community/blob/master/scripts/updateGithubStats.js#L23

We just got our first GitLab library resource with PR #150. The existing script doesn't break but it won't keep the GitLab stats in sync.

**Comment by swyxio** [comment]
yup!

**Comment by ryanatkn** [comment]
Thank you @loremaps!
