### ISSUE TITLE
awesome-svelte link in resources leads back here, remove?

### ISSUE THREAD

**Issue by FranciscoG** [sveltejs/community-legacy#197]
Hi

`awesome-svelte` from the resources page leads back to the here, should it be removed? replaced?

- Start here:
https://svelte-community.netlify.app/resources

- click on "awesome-svelte"
![Screen Shot 2020-05-05 at 10 47 45 PM](https://user-images.githubusercontent.com/557684/81134418-abab1f00-8f22-11ea-8afb-7131007e14cd.png)

- it takes you to: https://github.com/CalvinWalzel/awesome-svelte which has a big warning and link that leads you to this github repo.
![Screen Shot 2020-05-05 at 10 51 48 PM](https://user-images.githubusercontent.com/557684/81134552-1eb49580-8f23-11ea-824b-5ca946a88af6.png)

Should it be removed from here since it's no longer needed?
https://github.com/sveltejs/community/blob/master/data/resources.yml#L162

**Comment by swyxio** [comment]
sure.
