### ISSUE TITLE
add open graph tags

### ISSUE THREAD

**Issue by swyxio** [sveltejs/community-legacy#20]
for each page, add <og:*> metadata so this SEOs nicer and shows up nicer in unfurls. fun first project :)

**Comment by kalyssao** [comment]
hey! i'm interested in this issue - but I want to clarify - would this mean adding `<meta name=og:*/>` into each of the routes? and would '*' in this case represent the name of said route?

**Comment by swyxio** [comment]
something like that, yes! here are some examples you can steal to adapt. https://github.com/sw-yx/swyxdotio/blob/master/src/routes/writing/%5Bslug%5D.svelte#L51-L76 pr still welcome!

**Comment by kalyssao** [comment]
ahh I see - so the meta tags will be in the <svelte:head> tag of each of the pages. where do i get the seo titles & descriptions though?

**Comment by swyxio** [comment]
really up to you! i might make a little start on this if youre stuck

**Comment by kalyssao** [comment]
yes - i'd appreciate that! also sorry for the back and forth - it's my first issue, thus i don't want to mess anything up lol 😅

**Comment by Nuhvi** [comment]
I see this is still open, I will work on it tonight if no one minds!

**Comment by swyxio** [comment]
nice job @Nazeh !

**Comment by kalyssao** [comment]
ah my bad! thanks for showing me how it's done @Nazeh!
