### ISSUE TITLE
Allow sorting by GitHub stars

### ISSUE THREAD

**Issue by benmccann** [sveltejs/community-legacy#202]
https://svelte-community.netlify.app/code has a ton on it and can be difficult to navigate. Even when choosing a tag, there can still be a lot in a single category

**Comment by swyxio** [comment]
im fine with this, PR welcome! lets also sort by downloads

**Comment by benmccann** [comment]
`last_updated` would be a good sort option as well

**Comment by dreitzner** [comment]
https://sveltesociety.dev/
