### ISSUE TITLE
Page title says 404

### ISSUE THREAD

**Issue by benmccann** [sveltejs/community-legacy#205]
When I load https://svelte-community.netlify.app/code/ it says "Code • Svelte Community" for a second and then changes to "404 • Svelte Community"

**Comment by saikatdas0790** [comment]
It's quite simple really, we just need to add a redirects file like so. This is a netlify specific thing where you need to tell Netlify to always serve the index.html whenever any route is requested.

We can do this by adding a _redirects file to the public or build folder that is being served by Netlify. The contents of the _redirects file is 

/*    /index.html   200

And that's it. Here's the relevant [documentation](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file)

**Comment by dreitzner** [comment]
I believe this issue happens because the favicon is missing.....

I'll port it over from the svelte site....

**Comment by dreitzner** [comment]
The issue is a trailing slash
![image](https://user-images.githubusercontent.com/30938967/105548336-c5ce9c80-5cff-11eb-9772-16c57206f7c5.png)
