### ISSUE TITLE
[Event] New Meetup or Conference

### ISSUE THREAD

**Issue by jbblanc** [sveltejs/community-legacy#215]
Hi! I am planning to organize a new Svelte Meetup (and also Discovery Live Training). Here are the details:

    City: Paris (at first, then other cities around the country)
    Country: France
    Description: First official Meetup (and also Trainings) to have french developers discover and share about Svelte/Sapper (which I (as CTO of my startup studio - Rocket Studio France) now exclusively use with my teammates - around 6 developers - to build new innovative web platforms). 
    Event Name: To be defined, we're still brainstorming with the team !
    Organizer contact: Jean-Baptiste Blanc (myself) => jbb@rocketstud.io
    Twitter: 
    Type: Meetup (or Training Course on Svelte /Sapper)
    Url: www.rocketstud.io (sorry, French website and Svelte version is still under development -we focus more on our startups platforms development at the moment)
    Other relevant details: 1/ I wonder if this is possible to get our dedicated sveltesociety github repository (like some other cities from the society). 2/ We have dedicated office in Paris so we can host these first events until it gets too popular for our meetup room :-). 3/ I'd love to share with you our plans at Rocket Studio France around Svelte and Sapper for 2020 and next.

**Comment by swyxio** [comment]
nice! do you have a date for your first event?

**Comment by jbblanc** [comment]
Thanks for your quick reply @sw-yx .
I'm checking with the team to validate the date. This should be stated early this week. 
I keep you posted !

**Comment by dreitzner** [comment]
closed in favor of redirect to https://sveltesociety.dev/events
