### ISSUE TITLE
[umbrella] steal ideas from typescript community site

### ISSUE THREAD

**Issue by swyxio** [sveltejs/community-legacy#24]
TS is coincidentally embarking on the same thing we're doing and they have a bunch of good ideas and inspiration sources

- https://github.com/microsoft/TypeScript-Website/issues/63
- https://github.com/microsoft/TypeScript-Website/pull/88
- https://github.com/typescript-community
- https://github.com/typescript-community/governance/tree/docs

please make spinoff issues for stuff you want to work on if you have an idea you like and link back

**Comment by dreitzner** [comment]
closed in favor of redirect to https://sveltesociety.dev/
