### ISSUE TITLE
Embed the currently selected resource tags/categories and search in the url

### ISSUE THREAD

**Issue by ryanatkn** [sveltejs/community-legacy#25]
When someone asks "what routers does Svelte have?", you should be able to link to the resources with the "routers" tag/category selected, like `/resources/#tags=routers` or some other url format. It probably make senses to delay implementing this until we get a more stable design for tags/categories. (see #23)

Searches should be similarly mirrored in the url. Future UI state should likewise be easily added.

The window location should probably update as the user makes changes in the UI.

What url format makes the most sense? Hash, querystring, or a combination of a pushstate and hash/querystring like `/resources/tag/routers?search=boo`? The best answer may depend on the tags/categories design.

**Comment by swyxio** [comment]
ohh yea this is my jam. fyi i implemented this when i worked on the gatsby showcase https://www.gatsbyjs.org/showcase/?filters%5B0%5D=Agency. also the plugins experience https://www.gatsbyjs.org/plugins/?=firebase
