### ISSUE TITLE
Archive and redirect to Svelte Society?

### ISSUE THREAD

**Issue by kevmodrome** [sveltejs/community-legacy#281]
Should we try to move this stuff over to sveltesociety?

**Comment by swyxio** [comment]
i'm ok with it, but definitely feeling a bit of repo churn fatigue

**Comment by kevmodrome** [comment]
Yep! Same here

**Comment by frederikhors** [comment]
Please never get tired! You are wonderful!

Let's look together for a way to automate as much as possible?

**Comment by kevmodrome** [comment]
It's not going away, don't worry! There's already a semi-working component page on the sveltesociety website: https://sveltesociety.dev/components

You're very welcome to take it to the finish line! :)

**Comment by TheComputerM** [comment]
If you want you can take showcase entries from [here](https://github.com/TheComputerM/awesome-svelte/blob/master/index.js). This has a very easy [contributing](https://github.com/TheComputerM/awesome-svelte/blob/master/CONTRIBUTING.md) process to add new entries.

**Comment by benmccann** [comment]
I'm closing this so that we don't have any open issues an can archive the repo. I can't personally archive, but will ask around to see if someone is able to
