### ISSUE TITLE
image hosting

### ISSUE THREAD

**Issue by swyxio** [sveltejs/community-legacy#38]
cheap image hosting for now :) 

![image](https://user-images.githubusercontent.com/6764957/69814450-2c226280-11c2-11ea-9d5e-d3f7665ac95c.png)

**Comment by swyxio** [comment]
![image](https://user-images.githubusercontent.com/6764957/69814542-6986f000-11c2-11ea-8147-5342e21210fc.png)

**Comment by swyxio** [comment]
![image](https://user-images.githubusercontent.com/6764957/69814592-87eceb80-11c2-11ea-9f87-1536c5ce99ae.png)

**Comment by swyxio** [comment]
![image](https://user-images.githubusercontent.com/6764957/69814632-a0f59c80-11c2-11ea-92b0-93cc5b56bc0c.png)

**Comment by swyxio** [comment]
![image](https://user-images.githubusercontent.com/6764957/69814687-bb2f7a80-11c2-11ea-925a-0d6324670896.png)

**Comment by swyxio** [comment]
![image](https://user-images.githubusercontent.com/6764957/69814727-d26e6800-11c2-11ea-95d3-e4ac4c719fe7.png)

**Comment by swyxio** [comment]
![Uploading image.png…]()

**Comment by swyxio** [comment]
![image](https://user-images.githubusercontent.com/6764957/69814877-26794c80-11c3-11ea-999d-eeccf03f565c.png)

**Comment by swyxio** [comment]
![image](https://user-images.githubusercontent.com/6764957/69882772-45e5a780-129f-11ea-8ee9-23d7607b698a.png)

**Comment by swyxio** [comment]
https://celestrak.com/cesium/orbit-viz.php?tle=/pub/TLE/catalog.txt&satcat=/pub/satcat.txt&referenceFrame=1


![image](https://user-images.githubusercontent.com/6764957/69898032-be8d4800-1321-11ea-84f2-bc0e529e49c8.png)

**Comment by swyxio** [comment]
dek's js/webgl MMORPG https://u.teknik.io/rWquK.mp4

![image](https://user-images.githubusercontent.com/6764957/69898056-1deb5800-1322-11ea-9b14-91a72f7a9fc5.png)

**Comment by swyxio** [comment]
https://github.com/buhrmi/svelte-poker

https://camo.githubusercontent.com/081b1252caa70b4ab87e668b14e0da8f45bbaef2/68747470733a2f2f692e696d6775722e636f6d2f567344595932562e676966

**Comment by swyxio** [comment]
![image](https://user-images.githubusercontent.com/6764957/69898083-673ba780-1322-11ea-989e-5043eee0baca.png)

http://johanronsse.be/skilliverse-10/

**Comment by swyxio** [comment]
cool repls 

- region selector https://svelte.dev/repl/034bd1009d354178a9da6e58cb66d512?version=3.15.0
- responsive slider https://svelte.dev/repl/0add35f59c6148cc8e5a415b2e38c83a?version=3.15.0
- alert + auto close https://svelte.dev/repl/a6a467a7ddb84cef975d6d5a1174cbba?version=3.15.0

**Comment by kevmodrome** [comment]
![2019-10-26-conversation](https://user-images.githubusercontent.com/534488/69898733-72f88f80-135d-11ea-86fd-4a22014a6b69.jpg)

Convos IRC client front-end

**Comment by swyxio** [comment]
svelte gl boxes demo https://twitter.com/Rich_Harris/status/1200807516529147904

**Comment by antony** [comment]
@sw-yx you realise you don't need to actually commit your comment to save the image. Just drop it in here and copy the url.

**Comment by swyxio** [comment]
yeah 😅
