### ISSUE TITLE
Review and remove https://winston.appido.ir/ site

### ISSUE THREAD

**Issue by antony** [sveltejs/community-legacy#54]
It has been brought to our attention here https://github.com/sveltejs/svelte/issues/4001 that the Winston site might be illegally hosting videos.

I think since this is probably not something we want to encourage, and might be a legal grey area, that this particular site should be considered for removal.

**Comment by swyxio** [comment]
i'm fine with that.

**Comment by kevmodrome** [comment]
I have no problem with removing it either.

**Comment by ourway** [comment]
Just read this thread. As a developer, I have no info about the copyright of the website. I am just a developer using provided APIs, so there is no reason to remove it. It's sad that you reached this decision without due diligence. I think the website is a powerful example of how people can use Svelte.
