### ISSUE TITLE
Suggestion box

### ISSUE THREAD

**Issue by pngwn** [sveltejs/community-legacy#6]
It would be nice if there was a suggestion box of some description in case searching for events in a specific area yields no results. This would be a good way to see how much interest there would be in organising a meetup in that area. People who upvoted or added the suggestion could possibly be notified if an event ever does get organised in that area (or perhaps within a certain distance of that location).

@lukeed Requested this. If anything needs clarifying Luke is the one to ask!

**Comment by swyxio** [comment]
ah. we eat this stuff for breakfast at my day job. i think i have a good way to handle this ;)

**Comment by dreitzner** [comment]
closed in favor of redirect to https://sveltesociety.dev/
