### ISSUE TITLE
cookbook

### ISSUE THREAD

**Issue by swyxio** [sveltejs/community-legacy#7]
https://github.com/sveltejs/svelte/issues/2656

**Comment by swyxio** [comment]
How to use with Babel https://github.com/sveltejs/svelte/issues/3388#issuecomment-559520419

**Comment by induratized** [comment]
How to use `@babel/plugin-proposal-optional-chaining` with svelte, or any other `stage-3` feature ?

**Comment by yestoall** [comment]
did you find any solution to make it works?

**Comment by kevmodrome** [comment]
This is not the place for support, guys, you're much better off finding help on the Discord server @induratized @yestoall

**Comment by swyxio** [comment]
worth adding 7GUI's recipes https://eugenkiss.github.io/7guis/tasks/

**Comment by dreitzner** [comment]
closed in favor of redirect to https://sveltesociety.dev/recipes
