### ISSUE TITLE
I have a starter svelte boilerplate temlate. How to publish or added to this commnuity

### ISSUE THREAD

**Issue by mylastore** [sveltejs/community-legacy#89]
This is a starter [boilerplate template](https://github.com/mylastore/svelte-parcel)

**Comment by kevmodrome** [comment]
Do a PR to one of the files where the content is located. You can take a look at earlier PRs to see how they have done it. Please only use the tags that we have currently on the site.

**Comment by mylastore** [comment]
Sorry I am still lost I am kind of new to github, can you point me to to some examples or links to how to create a pull request?

**Comment by kevmodrome** [comment]
I understand! So, what you can do is fork the repo, there's a button in the top-right, do a commit and then you click the PR tab in the menu on the top here. It will show you your fork as well as this repo and you can decide if you want to make a PR or not :) GL!
